image:
  file: .gitpod.Dockerfile

vscode:
  extensions: 
    - ms-azuretools.vscode-docker

tasks:
  - init: npm install && npm run build

ports:
  - name: simple-server
    description: Simple 200 Response
    port: 8080
    onOpen: open-browser
    visibility: public